server:
  port: ${PORT:8086}
spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: "ClaveSuperSeguraJWTParaDuocUC2026SpringBoot"
  expiration-ms: 3600000

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8869/eureka/}
  instance:
    prefer-ip-address: true

