services:
  eureka-server:
    image: eureka-server
    build: ./eureka-server
    ports:
      - "8869:8869"



  gateway-service:
    image: gateway-service
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/


  cliente:
    image: clientes
    build: ./cliente
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/clientes?sslmode=REQUIRED


  mecanicos:
    image: mecanicos
    build: ./mecanicos
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/mecanicos?sslmode=REQUIRED




  corredorSeguro:
    image: corredorseguro
    build: ./corredorSeguro
    ports:
      - "8091:8091"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/corredorseguros?sslmode=REQUIRED





  personalaseo:
    image: personal-aseo
    build: ./personalaseo
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/personalaseo?sslmode=REQUIRED





  vehiculo:
    image: vehiculos
    build: ./vehiculo
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/vehiculo?sslmode=REQUIRED





  vendedor:
    image: vendedores
    build: ./vendedor
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/vendedor?sslmode=REQUIRED





  auth-service:
    image: auth-service
    build: ./auth-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/auth-service?sslmode=REQUIRED





  ventas-Update:
    image: ventas-update
    build: ./ventas-Update
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - cliente
      - vehiculo
      - vendedor
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/ventas?sslmode=REQUIRED





  testDrive:
    image: testdrive
    build: ./testDrive
    ports:
      - "8092:8092"
    depends_on:
      - eureka-server
      - cliente
      - vehiculo
      - vendedor
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/testdrives?sslmode=REQUIRED




  seguro:
    image: seguro
    build: ./seguro
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - cliente
      - vehiculo
      - corredorSeguro
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/seguros?sslmode=REQUIRED




  mantenciones:
    image: mantenciones
    build: ./mantenciones
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - cliente
      - vehiculo
      - mecanicos
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_tGFI6-cDzGVv9I_h9O9
      - DB_URL=jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/mantenciones?sslmode=REQUIRED





