services:
  eureka-server:
    image: eureka-server
    build: ./eureka-server
    ports:
      - "8869:8869"



  gateway-service:
    image: gateway-service
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/


  cliente:
    image: clientes
    build: ./cliente
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_CLIENTES}


  mecanicos:
    image: mecanicos
    build: ./mecanicos
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_MECANICOS}




  corredorSeguro:
    image: corredorseguro
    build: ./corredorSeguro
    ports:
      - "8091:8091"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_CORREDORSEGURO}





  personalaseo:
    image: personal-aseo
    build: ./personalaseo
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_PERSONALASEO}





  vehiculo:
    image: vehiculos
    build: ./vehiculo
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_VEHICULO}





  vendedor:
    image: vendedores
    build: ./vendedor
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_VENDEDOR}





  auth-service:
    image: auth-service
    build: ./auth-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_AUTHSERVICE}





  ventas-Update:
    image: ventas-update
    build: ./ventas-Update
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - cliente
      - vehiculo
      - vendedor
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_VENTAS}





  testDrive:
    image: testdrive
    build: ./testDrive
    ports:
      - "8092:8092"
    depends_on:
      - eureka-server
      - cliente
      - vehiculo
      - vendedor
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_TESTDRIVE}




  seguro:
    image: seguro
    build: ./seguro
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - cliente
      - vehiculo
      - corredorSeguro
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_SEGURO}




  mantenciones:
    image: mantenciones
    build: ./mantenciones
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - cliente
      - vehiculo
      - mecanicos
    environment:
      - EUREKA_URL=http://eureka-server:8869/eureka/
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${URL_MANTENCIONES}





