server:
    port: ${PORT:8084}

spring:
    application:
        name: mecanicos
    datasource:
        url: jdbc:h2:mem:db_mecanicos;DB_CLOSE_DELAY=-1;MODE=MySQL
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    enable-hateoas: false

logging:
    level:
        duoc.vendedor: INFO
        org.springframework.web: WARN
    file:
        name: logs/mecanico.log

eureka:
    client:
        enabled: ${EUREKA_ENABLED:true}
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8869/eureka/}
    instance:
        prefer-ip-address: true


jwt:
    secret: "ClaveSuperSeguraJWTParaDuocUC2026SpringBoot"
    expiration-ms: 3600000

