server:
  port: ${PORT:8091}
spring:
  application:
    name: corredorSeguro
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  enable-hateoas: false


logging:
  level:
    duoc.corredorSeguro: info
    org.springframework.web: warn
  file:
    name: logs/corredor.log

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8869/eureka/}
  instance:
    prefer-ip-address: true
app:
  discovery:
    enabled: ${APP_DISCOVERY_ENABLED:true}



