server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: corredores
              uri: ${CORREDOR_URL:lb://CORREDORSEGURO}
              predicates:
                - Path=/api/v1/corredores/**
            - id: clientes
              uri: ${CLIENTES_URL:lb://CLIENTE}
              predicates:
                - Path=/api/v1/clientes/**
            - id: mantencion
              uri: ${MANTENCIONES_URL:lb://MANTENCION}
              predicates:
                - Path=/api/v1/mantenciones/**
            - id: mecanicos
              uri: ${MECANICOS_URL:lb://MECANICOS}
              predicates:
                - Path=/api/v1/mecanicos/**
            - id: personalaseo
              uri: ${PERSONALASEO_URL:lb://PERSONALASEO}
              predicates:
                - Path=/api/v1/personalaseo/**
            - id: seguro
              uri: ${SEGURO_URL:lb://SEGURO}
              predicates:
                - Path=/api/v1/seguros/**
            - id: vehiculo
              uri: ${VEHICULO_URL:lb://VEHICULO}
              predicates:
                - Path=/api/v1/vehiculos/**
            - id: vendedor
              uri: ${VENDEDOR_URL:lb://VENDEDOR}
              predicates:
                - Path=/api/v1/vendedores/**
            - id: ventas-Update
              uri: ${VENTAS_UPDATE_URL:lb://VENTAS-UPDATE}
              predicates:
                - Path=/api/v1/ventas/**
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:lb://AUTH-SERVICE}
              predicates:
                - Path=/auth/**
            - id: testDrive
              uri: ${TEST_DRIVE_URL:lb://TESTDRIVE}
              predicates:
                - Path=/api/v1/testdrives/**


management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8869/eureka/}
  instance:
    prefer-ip-address: true