server:
  port: ${PORT:8092}

spring:
  application:
    name: testDrive
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  enable-hateoas: false

logging:
  level:
    duoc.testDrive: INFO
    org.springframework.web: WARN
  file:
    name: logs/testDrive.log

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8869/eureka/}
  instance:
    prefer-ip-address: true

services:
  cliente:
    url: ${CLIENTE_URL:http://CLIENTE}
  vehiculo:
    url: ${VEHICULO_URL:http://VEHICULO}
  vendedor:
    url: ${VENDEDOR_URL:http://VENDEDOR}

jwt:
  secret: "ClaveSuperSeguraJWTParaDuocUC2026SpringBoot"
  expiration-ms: 3600000
