server:
  port: ${PORT:8085}

spring:
  application:
    name: mantencion
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  enable-hateoas: false

logging:
  level:
    duoc.mantenciones: INFO
    org.springframework.web: WARN
  file:
    name: logs/mantencion.log

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8869/eureka/}
  instance:
    prefer-ip-address: true
app:
  discovery:
    enabled: ${APP_DISCOVERY_ENABLED:true}

services:
  cliente:
    url: ${CLIENTE_URL:http://CLIENTE}
  mecanico:
    url: ${MECANICOS_URL:http://MECANICOS}
  vehiculo:
    url: ${VEHICULO_URL:http://VEHICULO}

jwt:
  secret: "ClaveSuperSeguraJWTParaDuocUC2026SpringBoot"
  expiration-ms: 3600000


