server:
  port: ${PORT:8869}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8869/eureka/
  server:
    enable-self-preservation: false
