server:
  port: ${PORT:8081}

spring:
  application:
    name: vendedor
  datasource:
    url: jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/vendedor?sslmode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  enable-hateoas: false

logging:
  level:
    duoc.vendedor: INFO
    org.springframework.web: WARN
  file:
    name: logs/vendedor.log

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8869/eureka/}
  instance:
    prefer-ip-address: true


jwt:
  secret: "ClaveSuperSeguraJWTParaDuocUC2026SpringBoot"
  expiration-ms: 3600000

