spring:
  datasource:
    url: jdbc:mysql://automotoraduoc2026-duocautomotora2026.d.aivencloud.com:13319/clientes_dev?sslmode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update